mapr:
  drill:
    connection:
      jdbc:
        hosts: localhost
        connection_pattern: jdbc:drill:zk=%s/drill/%s-drillbits;auth=maprsasl
        driver: com.mapr.drill.jdbc42.Driver
        port: 31010
        clusterName: local
  ojai:
    url: "ojai:mapr:"
  rest:
    baseUrl: "https://localhost:"
    port: "8243"
    api: "/api/v2/table/"
  permissions:
    owner: "owner"
    group: "group"
    other: "other"
